# Generated by Django 5.2.6 on 2025-10-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_created_at_alter_chatroom_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group', 'Group'), ('private', 'Private')], default='group', max_length=10),
        ),
    ]
